# Generated by Django 5.2.6 on 2025-10-26 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shop_explanation', models.CharField(max_length=200)),
                ('near_station', models.CharField(max_length=200)),
                ('walk_minutes', models.PositiveIntegerField()),
                ('price_range', models.PositiveIntegerField()),
                ('business_hour_start', models.TimeField(verbose_name='営業時間（開始）')),
                ('business_hour_end', models.TimeField(verbose_name='営業時間（終了）')),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('max_reserve_num', models.PositiveIntegerField()),
                ('img', models.ImageField(blank=True, default='noImage.png', upload_to='')),
                ('shop_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.category')),
            ],
        ),
    ]
