# Generated by Django 5.2.6 on 2025-12-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_shop_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=300, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='店舗画像'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='max_reserve_num',
            field=models.PositiveIntegerField(verbose_name='予約可能人数'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='near_station',
            field=models.CharField(max_length=200, verbose_name='最寄駅'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_range',
            field=models.PositiveIntegerField(verbose_name='価格帯'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_explanation',
            field=models.CharField(max_length=200, verbose_name='店舗紹介'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='walk_minutes',
            field=models.PositiveIntegerField(verbose_name='徒歩時間'),
        ),
    ]
